PMAwesome/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from properties import views as propertiesViews
from messaging import views as messagingViews
from assets import views as assetViews

app_name = 'messaging'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', propertiesViews.property_list, name='index'),
    

    # Messaging ================
    url(r'^message/(?P<pk>\d+)/', messagingViews.message_detail, name='message_detail'),
    url(r'^messages/', messagingViews.message_list, name='message_list'),
    #url(r'^messages/', messagingViews.index, name='message_list'),
    
    url(r'^contact/(?P<pk>\d+)/modal', messagingViews.contact_detail_modal, name='contact_detail_modal'),
    url(r'^contact/(?P<pk>\d+)/', messagingViews.contact_detail, name='contact_detail'),
    url(r'^contacts/', messagingViews.contact_list, name='contact_list'),

    # Properties  ================
    url(r'^property/(?P<pk>\d+)/', propertiesViews.property_detail, name='property_detail'),
    url(r'^property/edit/(?P<pk>\d+)/', propertiesViews.property_edit, name='property_edit'),
    url(r'^property/new/$', propertiesViews.property_new, name='property_new'),
    url(r'^properties/', propertiesViews.property_list, name='property_list'),

    url(r'^lease/(?P<pk>\d+)/modal', propertiesViews.lease_detail_modal, name='lease_detail_modal'),
    url(r'^lease/edit/(?P<pk>\d+)/modal', propertiesViews.lease_edit_modal, name='lease_edit_modal'),
    url(r'^lease/add/(?P<pk>\d+)/modal', propertiesViews.lease_add_modal, name='lease_add_modal'),
    url(r'^lease/(?P<pk>\d+)/', propertiesViews.lease_detail, name='lease_detail'),

    # Assets ================
    url(r'^assets/reserved_keys/', assetViews.reserved_keys, name='reserved_keys'),
    
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

properties/models.py
import localflavor.us.models
import datetime, math
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.db import models
#from messaging.models import Contact, Message



# ================================================================
class Property(models.Model):

    name 			= models.CharField(max_length=50)
    slug            = models.CharField(max_length=100)

    # Location of the Property
    addressNumeric	= models.PositiveIntegerField(verbose_name='Street Numeric', help_text='Number only')
    addressStreet	= models.CharField(max_length=30, verbose_name='Street Name', help_text='Street name only, no numeric, no unit number.')
    addressUnit		= models.CharField(max_length=20, blank=True, verbose_name='Unit')
    addressCity		= models.CharField(max_length=20, verbose_name='City')
    addressState	= localflavor.us.models.USStateField(default='FL', verbose_name='State')
    addressZipcode	= localflavor.us.models.USZipCodeField(verbose_name='Zip Code')
    addressCounty	= models.CharField(max_length=20, verbose_name='County')
    
    addressFull		= models.CharField(max_length=100)
    addressShort    = models.CharField(max_length=50)    
    #addressStreet1	= models.CharField(max_length=50, blank=True)	# May not be necessary
    #addressStreet2	= models.CharField(max_length=50, blank=True)	# May not be necessary

    neighborhood	= models.CharField(max_length=30, blank=True)
    partOfTown		= models.CharField(max_length=30, blank=True, verbose_name='Part of Town')

    #mapping info
    isMapable		= models.BooleanField(default=False)
    mapNotes		= models.TextField(blank=True)
    mapLatitude		= models.FloatField(null=True, blank=True)
    mapLongitude	= models.FloatField(null=True, blank=True)

    # Features of the Property

    PROPERTY_TYPE_SINGLEFAMILY	= 'sfhouse'
    PROPERTY_TYPE_CONDO			= 'condo'
    PROPERTY_TYPE_TOWNHOUSE		= 'townhouse'
    PROPERTY_TYPE_COMMERCIAL	= 'commercial'
    PROPERTY_TYPE_CHOICES=(
        (PROPERTY_TYPE_SINGLEFAMILY, 'House'),
        (PROPERTY_TYPE_CONDO, 'Condo'),
        (PROPERTY_TYPE_TOWNHOUSE, 'Townhouse'),
        (PROPERTY_TYPE_COMMERCIAL, 'Commercial'),
    )

    propertyType    = models.CharField(max_length=20, choices=PROPERTY_TYPE_CHOICES, default=PROPERTY_TYPE_SINGLEFAMILY, verbose_name='Type of Property')
    areaHeatedSqFt	= models.PositiveIntegerField(null=True, blank=True, verbose_name='Heated Area')
    areaLotSqFt		= models.PositiveIntegerField(null=True, blank=True, verbose_name='Lot Area')
    bedrooms		= models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Bedrooms' )
    bathroomsFull	= models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Full Bathrooms')
    bathroomsHalf	= models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Half Bathrooms')
    yearBuilt		= models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Year Built')

    petCatsOK       = models.BooleanField(default=True, verbose_name='Cats OK?')
    petDogsOK       = models.BooleanField(default=True, verbose_name='Dogs OK?')
    petRestrictions = models.CharField(max_length=100, blank=True, null=True, verbose_name='Pet Restrictions')

    marketingDescription = models.TextField(null=True, blank=True, verbose_name='Marketing Description')

    dateContractStart = models.DateField(blank=True, null=True, verbose_name='Contract Start Date')
    contactManager  = models.ForeignKey('messaging.Contact', on_delete=models.CASCADE, blank=True, null=True, limit_choices_to={'isStaff': True}, verbose_name='Property Manager')

    ext_appfolioID  = models.CharField(max_length=40, blank=True, null=True, verbose_name='Appfolio ID')
    ext_MLSID       = models.CharField(max_length=20, blank=True, null=True, verbose_name='MLS ID')


    HOA_name             = models.CharField(max_length=50, blank=True, null=True, verbose_name='HOA Name')
    HOA_email            = models.EmailField(blank=True, null=True, verbose_name='HOA Email')
    HOA_phone            = localflavor.us.models.PhoneNumberField(blank=True, null=True, verbose_name='HOA Phone')

    HOA_approvesTenants  = models.BooleanField(default=False, verbose_name='HOA Approves Tenants')
    HOA_gateCode         = models.CharField(max_length=20, blank=True, null=True, verbose_name='Gate Code')

    system_isWellWater              = models.BooleanField(default=False, verbose_name='On Well Water?')    
    system_isSeptic                 = models.BooleanField(default=False, verbose_name='On Septic?')
    system_mainWaterShutoff         = models.CharField(max_length=20, blank=True, null=True, verbose_name='Main Water Shut Off')    
    system_refrigeratorWaterShutoff = models.CharField(max_length=20, blank=True, null=True, verbose_name='Refrigerator Water Shut Off')    
    system_excludedItems            = models.CharField(max_length=100, blank=True, null=True, verbose_name='Excluded Items', help_text='List the areas or items in the home that are excluded from tenant use')
    system_irrigationController     = models.CharField(max_length=20, blank=True, null=True, verbose_name='Irrigation Controller')
    system_irrigationSchedule       = models.CharField(max_length=40, blank=True, null=True, verbose_name='Irrigation Schedule')


    POOL_NONE		= 'none'
    POOL_PRIVATE	= 'private'
    POOL_COMMUNITY	= 'community'
    POOL_BOTH		= 'both'
    POOL_CHOICES	= (
        (POOL_NONE, 'None'), 
        (POOL_PRIVATE, 'Private'),
        (POOL_COMMUNITY, 'Community'),
        (POOL_BOTH, 'Both'),
    )
    poolType		= models.CharField(max_length=10, choices=POOL_CHOICES, default=POOL_NONE, verbose_name='Pool Type')


    archived_on		= models.DateTimeField(blank=True, null=True, verbose_name='Archive On')

    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
   
    def hasPool(self):
        return self.poolType != self.POOL_NONE

    def bathrooms(self):
        return self.bathroomsFull.__str__() +'.'+ self.bathroomsHalf.__str__()

    def currentLease(self):
        today = datetime.date.today()
        leases = self.lease_set.filter(dateLeaseStart__lte=today, dateLeaseEnd__gte=today)
        if (len(leases) > 0):
            return leases[0]

    def futureLease(self):
        today = datetime.date.today()
        leases = self.lease_set.filter(dateLeaseStart__gte=today).order_by('dateLeaseStart')
        if (len(leases) > 0):
            return leases[0]

    def previousLease(self):
        today = datetime.date.today()
        leases = self.lease_set.filter(dateLeaseEnd__lte=today).order_by('-dateLeaseEnd')
        if (len(leases) > 0):
            return leases[0]

    def daysVacant(self):
        dv = 0
        today = datetime.date.today()

        if (self.currentLease() != None):
            dv = 0
        elif (self.previousLease() != None):
            diff = self.previousLease().dateLeaseEnd
            dv = diff.days
        else:
            dv = (today - self.dateContractStart).days
        return dv
    
    def daysTillMoveIn(self):
        if (self.futureLease() != None):
            today = datetime.date.today()
            return (self.futureLease().dateLeaseStart - today).days

    def daysBetweenLeases(self):
        if (self.futureLease() != None):
            d1 = None
            d2 = None
            if (self.previousLease() != None):
                d1 = self.previousLease().dateLeaseEnd
            elif (self.currentLease() != None):
                d1 = self.currentLease().dateLeaseEnd
            else:
                d1 = self.dateContractStart

            if (d1 != None):
                d2 = self.futureLease().dateLeaseStart
                if (d2 != None):
                    return (d2 - d1).days

    def percentBetweenLeases(self):
        if (self.daysVacant() and self.daysBetweenLeases()):
            return round(self.daysVacant() / self.daysBetweenLeases() * 100)
        else:
            return 0

    def addLog(self, notes):
        self.addActivity(
            notes = notes,
            priority = PropertyActivity.PRIORITY_LOG,
            type = PropertyActivity.TYPE_INFO
        )
        # newActivity = PropertyActivity(
        #     prop            = self,
        #     notes           = notes, 
        #     priority        = PropertyActivity.PRIORITY_LOG,
        #     type            = PropertyActivity.TYPE_INFO,
        #     activity_on     = timezone.datetime.now(),
        #     alertStart_on   = datetime.date.today(),
        #     )
        # newActivity.save()

    def addActivity(self, notes="", priority='low', type='info', activity_on = timezone.datetime.now(), alertStart_on   = datetime.date.today()):
        newActivity = PropertyActivity(
            prop            = self,
            notes           = notes, 
            priority        = priority,
            type            = type,
            activity_on     = activity_on,
            alertStart_on   = alertStart_on,
            )
        newActivity.save()


    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Properties'
        ordering = ["name"]

    def save(self, *args, **kwargs):
        # rebuild address short strings
        self.addressShort = self.addressNumeric.__str__() +' '+ self.addressStreet
        self.name = self.addressStreet +' '+ self.addressNumeric.__str__()
        if (self.addressUnit.strip() != ''):
            self.addressShort += ', '+ self.addressUnit
            self.name += ' '+ self.addressUnit
        
        self.addressFull = self.addressShort +', '+ self.addressCity +', '+ self.addressState +', '+ self.addressZipcode
        self.slug = slugify(self.addressFull)
        
        super(Property, self).save(*args, **kwargs)

        # log the creation of the property
        self.addLog('Property saved')


# ================================================================

properties/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .forms import *

import datetime

# import model
from .models import *
from assets.models import ReservedKey


def index(request):
    return HttpResponse('Property Dashboard')


def property_list(request):
    today = datetime.datetime.now()

    propFilter = Q(archived_on=None) | Q(archived_on__gt=today)  # remove any archived results
    if (request.GET.get('showArchived') == '1'):
        propFilter = Q(archived_on__lte=today)  # remove any archived results

    properties = Property.objects.filter(propFilter).order_by('-created_on')[:100]

    # alerts
    rangeStart = today - datetime.timedelta(days=(30 * 2))
    rangeEnd = today + datetime.timedelta(days=(30 * 4))
    propActivities = PropertyActivity.objects.filter(activity_on__gte=rangeStart, activity_on__lte=rangeEnd,
                                                     priority__gte=PropertyActivity.PRIORITY_LOW).only('prop', 'type',
                                                                                                       'priority',
                                                                                                       'activity_on').order_by(
        '-activity_on')

    return render(request, 'property_list.html', {
        'properties': properties,
        'propActivities': propActivities,
        'browserTitle': 'Properties List',
        'pageHeader': 'Properties',
        'breadCrumb1': 'Property List'
    })


def property_detail(request, pk):
    prop = get_object_or_404(Property, pk=pk)

    leaseHistory = prop.lease_set.order_by('-dateLeaseStart')

    owners = prop.propertyowner_set.order_by('-percentageShare')
    currentLease = prop.currentLease()

    if currentLease is not None:
        leaseContacts = currentLease.leasecontact_set.exclude(type=LeaseContact.TYPE_OWNER).order_by('-type',
                                                                                                     'contact__nameFirst')
    else:
        leaseContacts = None

    propActivities = PropertyActivity.objects.filter(prop=pk, priority__gte=PropertyActivity.PRIORITY_LOG).order_by(
        '-activity_on')

    try:
        resKey = prop.reservedkey
    except ReservedKey.DoesNotExist:
        resKey = None

    # import pdb; pdb.set_trace()


    return render(request, 'property_detail.html', {
        'prop': prop,
        'resKey': resKey,
        'leaseHistory': leaseHistory,
        'currentLease': currentLease,
        'owners': owners,
        'contacts': leaseContacts,
        'propActivities': propActivities,
        'browserTitle': prop.name + ': Property Details',
        'pageHeader': prop.name,
        'breadCrumb1': 'Property List',
        'breadCrumb2': 'Property Detail'
    })


def property_new(request):
    if request.method == 'POST':
        form = PropForm(request.POST)
        # return HttpResponse(form)
        if form.is_valid():
            # process the data in form.cleaned_data
            form.save()
            # redirect to detail page
            return HttpResponseRedirect('/properties')

    else:
        form = PropForm()

    return render(request, 'property_edit.html', {
        'form': form,
        'browserTitle': 'Creating New Property',
        'pageHeader': 'Creating New Property',
        'breadCrumb1': 'Property List',
        'breadCrumb2': 'Property New',
    })


def property_edit(request, pk):
    prop = get_object_or_404(Property, pk=pk)

    if request.method == 'POST':

        form = PropForm(request.POST, instance=prop)
        # return HttpResponse(form)
        if form.is_valid():
            # process the data in form.cleaned_data
            form.save()
            # redirect to detail page
            return HttpResponseRedirect('/property/'+ prop.id.__str__())

    else:
        form = PropForm(instance=prop)

    return render(request, 'property_edit.html', {
        'form': form,
        'prop': prop,
        'browserTitle': 'Editing ' + prop.name,
        'pageHeader': prop.name,
        'breadCrumb1': 'Property List',
        'breadCrumb2': 'Property Edit',
    })


def lease_detail(request, pk):
    lease = get_object_or_404(Lease, pk=pk)

    return render(request, 'lease_detail.html', {
        'browserTitle': 'Lease Editing',
        'pageHeader': lease.prop,
        'lease': lease
    })

def lease_detail_modal(request, pk):
    lease = get_object_or_404(Lease, pk=pk)

    return render(request, 'lease_detail_modal.html', {
        'browserTitle': 'Lease Editing',
        'pageHeader': lease.prop,
        'lease': lease
    })

def lease_add_modal(request, pk):
    prop = get_object_or_404(Property, pk=pk)

    if request.method == 'POST':
        form = LeaseForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/property/'+ prop.id.__str__())
    else:
        form = LeaseForm()

    return render(request, 'lease_add_modal.html', {
        'pageHeader': 'Add a New Lease',
        'form': form,
        'prop': prop,
    })



def lease_edit_modal(request, pk):
    lease = get_object_or_404(Lease, pk=pk)

    if request.method == 'POST':
        form = LeaseForm(request.POST, instance=lease)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/property/'+ lease.prop_id.__str__())
    else:
        form = LeaseForm(instance=lease)

    return render(request, 'lease_edit_modal.html', {
        'form': form,
        'pageHeader': 'Edit This Lease',
    })

properties/templates/lease_add_modal.html
{% extends 'base_modal_window.html' %}
{% load bootstrap_tags %}


{% block contentModal %}
<div class="row">
    <div class="ibox">
        <div class="ibox-content">
            <form class="form form-horizontal" method="post">
                {% csrf_token %}

                <!-- Inspinia Auto Generated by Django ======================================== -->
                {{form | as_bootstrap_horizontal}}

                <input type="hidden" name="id_id" default="{{prop.pk}}">
                <div class="form-group">
                    {% if prop.pk != None %}
                        <a href="{% url 'property_detail' prop.pk %}" class="btn btn-white" type="submit">Cancel</a>
                    {% else %}
                        <a href="{% url 'property_list' %}" class="btn btn-white" type="submit">Cancel</a>
                    {% endif %}
                    <button class="btn btn-primary" type="submit">Save changes</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

properties/templates/lease_edit_modal.html
{% extends 'base_modal_window.html' %}
{% load bootstrap_tags %}


{% block contentModal %}
<div class="row">
    <div class="ibox">
        <div class="ibox-content">
            <form class="form form-horizontal" method="post">
                {% csrf_token %}

                <!-- Inspinia Auto Generated by Django ======================================== -->
                {{form | as_bootstrap_horizontal}}

                <input type="hidden" name="id_id" default="{{prop.pk}}">
                <div class="form-group">
                    {% if prop.pk != None %}
                        <a href="{% url 'property_detail' prop.pk %}" class="btn btn-white" type="submit">Cancel</a>
                    {% else %}
                        <a href="{% url 'property_list' %}" class="btn btn-white" type="submit">Cancel</a>
                    {% endif %}
                    <button class="btn btn-primary" type="submit">Save changes</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

properties/templates/property_detail.html
{% extends 'baseTwoColumn.html' %}



<!-- Property Activity -->
{% block contentMain %}


        <!-- Summary ============================================================================ -->
        {% include "property_detail__summary.html" %}

        <!-- Tabs ============================================================================== -->

        <div class="ibox">
            <div class="ibox-content">
                <div class="row m-t-sm">
                    <div class="col-lg-12">
                    <div class="panel blank-panel">
                    <div class="panel-heading">
                        <div class="panel-options">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab-1" data-toggle="tab">Activity Feed</a></li>
                                <li class=""><a href="#tab-2" data-toggle="tab">Lease History</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="panel-body">

                    <div class="tab-content">
                    <div class="tab-pane active" id="tab-1">

                        {% include "property_detail__activity_list.html" %}

                    </div>
                    <div class="tab-pane" id="tab-2">

                        {% include "property_detail__lease_history.html" %}

                    </div>
                    </div>

                    </div>

                    </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock contentMain %}




<!-- Property Description -->
{% block contentSide %}
    {% include "property_detail__side_content.html" %}

{% endblock contentSide %}

properties/templates/property_detail__activity_list.html
{% load humanize %}

<style>
    .timeline-item .date { width: 160px }
</style>




<div class="row">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Activities at this Property</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#">Config option 1</a>
                    </li>
                    <li><a href="#">Config option 2</a>
                    </li>
                </ul>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>

        <div class="ibox-content inspinia-timeline">

            {% for activity in propActivities %}
            
                <div class="timeline-item">
                    <div class="row">
                        <div class="col-xs-3 date">
                            
                            <i class="{{activity.type_icon}} bg-{{activity.priority_style}}"></i>

                            <small>{{activity.get_type_display}}</small>
                            <br/>
                           
                            {% if activity.isFuture %}
                                <small class="text-navy">{{activity.activity_on | naturalday | title}}</small>
                            {% else %}
                                <small class="text-muted">{{activity.activity_on | naturalday | title}}</small>
                            {% endif %}
                        </div>
                        <div class="col-xs-10 content no-top-border">
                            <div class="pull-right text-right">
                                <small>
                                    
                                    {% if activity.isFuture %}
                                        <small class="text-navy">{{activity.activity_on | timeuntil }} from now</small>
                                    {% else %}
                                        <small class="text-muted">{{activity.activity_on | timesince }} ago</small>
                                    {% endif %}
                                </small>                                    
                            </div>
                            <p class="m-b-xs"><strong>{{activity.type_verbose | title}}</strong></p>

                            {% if activity.notes != "" %}
                                <p>{{activity.notes}}</p>                            
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
    


</div>

properties/templates/property_detail__side_content.html
{% load humanize %}

<div class="wrapper wrapper-content project-manager side-summary small">
    <h4>{{prop.addressStreet1}}</h4>
    <!-- <img src="img/zender_logo.png" class="img-responsive"> -->

    <div class="pull-right">
        <a href="{% url 'property_edit' prop.pk %}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Edit</a>
    </div>

    <p class="small">
        {{ prop.addressFull }}
    </p>

    <h5>Location</h5>
    <dl class="dl-horizontal">
        <dt>City:</dt>      <dd>{{prop.addressCity}}</dd>
        <dt>County:</dt>    <dd>{{prop.addressCounty}}</dd>
        <dt>Zipcode:</dt>    <dd>{{prop.addressZipcode}}</dd>
        <dt>Hood:</dt>    <dd>{{prop.neighborhood}}</dd>
        <dt>Location:</dt>    <dd>{{prop.partOfTown}}</dd>

        <dt>Short:</dt>    <dd>{{prop.addressShort}}</dd>
        <dt>Full:</dt>    <dd>{{prop.addressFull}}</dd>
        <dt>Name:</dt>    <dd>{{prop.name}}</dd>
        <dt>Slug:</dt>    <dd>{{prop.slug}}</dd>
    </dl>

    <h5>About This Property</h5>            
    <dl class="dl-horizontal">
        <dt>Type:</dt>    <dd>{{prop.get_propertyType_display}}</dd>
        <dt>Rooms:</dt>    <dd>{{prop.bedrooms}} beds / {{prop.bathrooms}} baths</dd>
        <dt>Area:</dt>    <dd>{{prop.areaHeatedSqFt | intcomma}}</dd>
        <dt>Built:</dt>    <dd>{{prop.yearBuilt}}</dd>
        <dt>Pool:</dt>    <dd>{{prop.get_poolType_display}}</dd>
        <dt>Pets:</dt>      
        <dd>
            {% if prop.petDogsOK == True %}
                <div class="text-info"><i class="fa fa-paw"></i> Dogs OK</div>
            {% else %}
                <div class="text-danger"><i class="fa fa-paw"></i> No Dogs!</div>                
            {% endif %}
            
            {% if prop.petCatsOK == True %}
                <div class="text-info"><i class="fa fa-paw"></i> Cats OK</div>
            {% else %}
                <div class="text-danger"><i class="fa fa-paw"></i> No Cats!</div>                
            {% endif %}

            {% if prop.petRestrictions != None %}
                <div class="">
                    <a class="text-warning" data-toggle="popover" data-placement="left" data-content="{{prop.petRestrictions}}">
                        <i class="fa fa-exclamation-circle"></i> View Restrictions
                    </a>
                </div>
            {% endif %}
        </dd>
    </dl>

    {% if prop.marketingDescription %}
        <h5>Description</h5>
        <p style="padding-left: 2em;">{{prop.marketingDescription}}</p>
    {% endif %}

    <h5>Owner's Contract Info</h5>
    <dl class="dl-horizontal">
        <dt>Start:</dt>                     <dd>{{prop.dateContractStart}}</dd>
        <dt>Manager:</dt>                   <dd>{{prop.contactManager}}</dd>
        <dt>Renewal Fee:</dt>               <dd>$XXX </dd>
        <dt>First Rental Commission:</dt>   <dd>XX% </dd>
        <dt>Re-rental Commission:</dt>      <dd>XX% </dd>
        <dt>Reserved Key</dt>
        <dd>
            {% if resKey %}
                <a href="{% url 'reserved_keys' %}">{{ resKey.spot }}</a>
            {% else %}
                <a href="{% url 'reserved_keys' %}" class="text-warning">
                    <i class="fa fa-exclamation-circle"></i>
                    None
                </a>
            {% endif %}
        </dd>
    </dl>

    {% if prop.HOA_name %}
        <h5>Community Association</h5>
        <dl class="dl-horizontal">
            <dt>Name</dt>                   <dd>{{prop.HOA_name}}</dd>
            <dt>Email</dt>                  <dd><a href="mailto:{{prop.HOA_email}}">{{prop.HOA_email}}</a></dd>
            <dt>Phone</dt>                  <dd><a href="mailto:{{prop.HOA_phone}}">{{prop.HOA_phone}}</a></dd>
            <dt>Approval?</dt>              <dd>{{prop.HOA_approvesTenants | yesno:"Approves,Does Not Approve"}}</dd>
            <dt>Gate Code</dt>              <dd>{{prop.gateCode}}</dd>
        </dl>
    {% endif %}

    <h5>Propery Systems</h5>
    <dl class="dl-horizontal">
        <dt>Well Water</dt>
        <dd>{{prop.system_isWellWater | yesno}}</dd>
        <dt>Septic</dt>
        <dd>{{prop.system_isWellWater | yesno}}</dd>
        <dt>Fridge Shutoff</dt>
        <dd>{{prop.system_refrigeratorWaterShutoff}}</dd>
        <dt>Excluded Items</dt>
        <dd>{{prop.system_excludedItems}}</dd>
        <dt>Irrigation Controller</dt>
        <dd>{{prop.system_irrigationController}}</dd>
        <dt>Irrigiation Schedule</dt>
        <dd>{{prop.system_irrigationSchedule}}</dd>
    </dl>
   
</div>

properties/templates/property_edit.html
{% extends 'baseTemplate.html' %}
{% load bootstrap_tags %}
 

{% block content %}
<div class="row">
<div class="ibox col-md-6 col-md-offset-3">
    <div class="ibox-content">
        <form class="form form-horizontal" method="post">
            {% csrf_token %}

            <!-- Inspinia Auto Generated by Django ======================================== -->
            {{form | as_bootstrap_horizontal}}

            <input type="hidden" name="id_id" default="{{prop.pk}}">
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                    {% if prop.pk != None %}
                        <a href="{% url 'property_detail' prop.pk %}" class="btn btn-white" type="submit">Cancel</a>                    
                    {% else %}
                        <a href="{% url 'property_list' %}" class="btn btn-white" type="submit">Cancel</a>                    
                    {% endif %}
                    <button class="btn btn-primary" type="submit">Save changes</button>
                </div>
            </div>
        </form>

    </div>
</div>
</div>
{% endblock %}